=== pomidorka1515/vpn-sub/config.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "VPN Config",
    "type": "object",
    "required": [
        "uri", "api_token", "api_admin_ui_auth", "provider_id", "panel_alert_cooldown", "salt", "fingerprints", "nodes", "bot", "routing",
        "json_template", "bypass_packages", "domain", "ping_check_url",
        "publicbot", "codes", "3xui", "sub_name", "description", "flags",
        "users", "tokens", "displaynames", "tgids",
        "bw", "wl_bw", "profiles", "json_profiles", "profileDescriptions", "whitelistProfiles",
        "masterLinks", "profileNodes", "shortProfileDescriptions", "userFingerprints",
        "time", "status", "statusTime", "statusWl",
        "_notified", "_wl_notified"
    ],
    "additionalProperties": false,
    "properties": {
        "$schema": { "type": "string", "description": "Schema file." },
        "uri": { "type": "string", "description": "Main URI for the service.", "default": "sub" },
        "api_uri": { "type": "string", "description": "Admin API URI." },
        "api_admin_ui_auth": {
        	"type": "array",
        	"prefixItems": [
        		{ "type": "string", "description": "Username"},
        		{ "type": "string", "description": "Password"}
        	],
        	"items": false,
        	"minItems": 2,
        	"maxItems": 2
        },
        "provider_id": { "type": "string" },
        "fallback_domain": { "type": "string", "description": "Fallback domain to retrieve the subscription from. Only works with Happ and if provider id is present.\nMust host a mirror of this service." },
        "api_token": { "type": "string", "description": "Admin API Access token." },
        "panel_alert_cooldown": { "type": "integer", "description": "Panel alert cooldown in seconds.", "default": 3600 },
        "domain": { "type": "string", "description": "Your domain." },
        "ping_check_url": { "type": "string", "description": "URL used for checking connectivity in Happ, works with provider id only, must return 204." },
        "salt": { "type": "string", "description": "Salt for passwords, pick something strong." },
        "sub_name": { "type": "string", "description": "Text displayed in VPN clients." },

        "fingerprints": {
            "type": "array",
            "items": { "type": "string" },
            "uniqueItems": true,
            "default": ["safari", "chrome", "edge", "firefox"],
            "description": "List of allowed fingerprints. Dont add anything invalid, see xray uTLS section for the full list."
        },

        "nodes": {
            "type": "object",
            "additionalProperties": { "type": "string" },
            "description": "List of nodes. Must be raw domains or IPs."
        },

        "bot": {
            "type": "object",
            "required": ["token", "whitelist"],
            "additionalProperties": false,
            "description": "Admin bot configuration object.",
            "properties": {
                "token": { "type": "string", "description": "Token for your admin bot." },
                "whitelist": {
                    "type": "array",
                    "description": "List of users who are allowed to use the admin bot (UIDs)",
                    "default": [],
                    "items": { "type": "integer" }
                }
            }
        },

        "routing": {
            "type": "object",
            "description": "Happ routing object. Leave blank to disable.",
            "default": {},
            "required": ["Name", "GlobalProxy", "DomainStrategy", "DirectSites", "DirectPackages", "DirectIp"],
            "properties": {
                "Name": { "type": "string" },
                "GlobalProxy": { "type": "boolean" },
                "DomainStrategy": { "type": "string" },
                "DirectSites": { "type": "array", "items": { "type": "string" } },
                "DirectPackages": { "type": "array", "items": { "type": "string" } },
                "DirectIp": { "type": "array", "items": { "type": "string" } }
            }
        },

        "json_template": {
            "type": "object",
            "description": "JSON Profile template.",
            "default": {},
            "required": ["dns", "routing", "inbounds", "outbounds", "remarks"],
            "properties": {
                "servers": {
                    "type": "object",
                    "additionalProperties": false,
                    "required": ["servers", "queryStrategy"],
                    "properties": {
                        "servers": { "type": "array" },
                        "queryStrategy": { "type": "string" }
                    }
                },
                "routing": {
                    "type": "object",
                    "additionalProperties": true,
                    "required": ["rules", "domainStrategy"],
                    "$comment": "im not writing a full schema"
                }
            },
            "additionalProperties": true
        },

        "bypass_packages": {
        	"type": "array",
        	"description": "List of packages (android) to bypass",
        	"items": { "type": "string" }
        },
        
        "webui_passwords": {
            "type": "object",
            "description": "WebUI hashed passwords.",
            "additionalProperties": { "type": "string" }
        },
        "webui_users": {
            "type": "object",
            "description": "WebUI references \"external_username\": \"internal_username\"",
            "additionalProperties": { "type": "string" }
        },

        "funny_strings": {
            "type": "array",
            "description": "type shit",
            "items": { "type": "string" }
        },

        "publicbot": {
            "type": "object",
            "description": "Object for the public bot.",
            "required": ["token", "tg_lang", "lang"],
            "additionalProperties": false,
            "properties": {
                "token": { "type": "string" },
                "tg_lang": {
                    "type": "object",
                    "additionalProperties": { "type": "string", "enum": ["ru", "en"] }
                },
                "lang": {
                    "type": "object",
                    "required": ["ru", "en"],
                    "additionalProperties": false,
                    "properties": {
                        "ru": { "$ref": "#/$defs/langStrings" },
                        "en": { "$ref": "#/$defs/langStrings" }
                    }
                }
            }
        },

        "codes": {
            "type": "array",
            "description": "Object of codes.",
            "items": {
                "type": "object",
                "required": ["code", "action", "perma", "days", "gb"],
                "additionalProperties": false,
                "properties": {
                    "code": { "type": "string" },
                    "action": { "type": "string", "enum": ["register", "bonus"] },
                    "perma": { "type": "boolean" },
                    "days": { "type": "integer", "minimum": 0 },
                    "gb": { "type": "integer", "minimum": 0 },
                    "wl_gb": { "type": "integer", "minimum": 0 }
                }
            }
        },

        "3xui": {
            "type": "object",
            "description": "3x-ui panels.",
            "additionalProperties": {
                "type": "object",
                "required": ["name", "address", "port", "uri", "username", "password", "https", "whitelist", "ignore_inbounds"],
                "additionalProperties": false,
                "properties": {
                    "name": { "type": "string" },
                    "address": { "type": "string" },
                    "port": { "type": ["string", "integer"] },
                    "uri": { "type": "string" },
                    "username": { "type": "string" },
                    "password": { "type": "string" },
                    "https": { "type": "boolean" },
                    "whitelist": { "type": "boolean" },
                    "nginx_auth": {
                        "type": "array",
                        "items": { "type": "string" },
                        "minItems": 2,
                        "maxItems": 2
                    },
                    "ignore_inbounds": {
                        "type": "array",
                        "items": { "type": "integer" }
                    },
                    "inject_headers": { "type": "object" }
                }
            }
        },

        "description": {
            "type": "array",
            "items": { "type": "string" },
            "minItems": 14,
            "maxItems": 14
        },

        "flags": {
            "type": "object",
            "additionalProperties": { "type": "string" }
        },

        "users": {
            "type": "object",
            "additionalProperties": {
                "type": "string",
                "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
            }
        },

        "tokens": {
            "type": "object",
            "additionalProperties": { "type": "string" }
        },

        "displaynames": {
            "type": "object",
            "additionalProperties": { "type": "string" }
        },

        "tgids": {
            "type": "object",
            "additionalProperties": { "type": "string" }
        },

        "bw": {
            "type": "object",
            "additionalProperties": { "$ref": "#/$defs/bwEntry" }
        },

        "wl_bw": {
            "type": "object",
            "additionalProperties": { "$ref": "#/$defs/bwEntry" }
        },

        "profiles": {
            "type": "object",
            "additionalProperties": { "$ref": "#/$defs/bilingualPair" }
        },
        
        "json_profiles": { "type": "object" },

        "profileDescriptions": {
            "type": "object",
            "additionalProperties": { "$ref": "#/$defs/bilingualPair" }
        },

        "whitelistProfiles": {
            "type": "array",
            "items": { "type": "string" }
        },

        "xhttpExtra": {
            "type": "object",
            "additionalProperties": { "type": "object" }
        },

        "masterLinks": {
            "type": "object",
            "additionalProperties": { "type": "string" }
        },

        "profileNodes": {
            "type": "object",
            "additionalProperties": { "type": "string" }
        },

        "shortProfileDescriptions": {
            "type": "object",
            "additionalProperties": { "$ref": "#/$defs/bilingualPair" }
        },

        "userFingerprints": {
            "type": "object",
            "additionalProperties": { "type": "string" }
        },

        "time": {
            "type": "object",
            "additionalProperties": { "type": "integer", "minimum": 0 }
        },

        "status": {
            "type": "object",
            "additionalProperties": { "type": "boolean" }
        },

        "statusTime": {
            "type": "object",
            "additionalProperties": { "type": "boolean" }
        },

        "statusWl": {
            "type": "object",
            "additionalProperties": { "type": "boolean" }
        },

        "_notified": {
            "type": "array",
            "items": { "type": ["integer", "null"] }
        },

        "_wl_notified": {
            "type": "array",
            "items": { "type": ["integer", "null"] }
        },

        "_last_reset": {
            "type": "string",
            "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
        },

        "_last_reset_month": {
            "type": "string",
            "pattern": "^\\d{4}-(0[1-9]|1[0-2])$"
        }
    },

    "$defs": {
        "bwEntry": {
            "type": "array",
            "prefixItems": [
                { "type": "integer", "minimum": 0, "description": "limit in GB, 0 = unlimited" },
                { "type": "integer", "minimum": 0, "description": "used bytes this month" }
            ],
            "items": false,
            "minItems": 2,
            "maxItems": 2
        },
        "bilingualPair": {
            "type": "array",
            "items": { "type": "string" },
            "minItems": 2,
            "maxItems": 2
        },
        "langStrings": {
            "type": "object",
            "additionalProperties": { "type": "string" }
        }
    }
}

=== pomidorka1515/vpn-sub/docs/EXAMPLE.config.json
{
    "$schema": "../config.schema.json",
    "uri": "sub",
    "api_uri": "",
    "provider_id": "",
    "api_token": "",
    "api_admin_ui_auth": [
        "username",
        "password"
    ],
    "panel_alert_cooldown": 3600,
    "domain": "",
    "fallback_domain": "",
    "ping_check_url": "",
    "salt": "",
    "fingerprints": [
        "safari",
        "chrome",
        "edge",
        "firefox"
    ],
    "nodes": {
        "n1": ""
    },
    "bot": {
        "token": "",
        "whitelist": []
    },
    "routing": {
        "Name": "",
        "GlobalProxy": true,
        "DomainStrategy": "IPIfNonMatch",
        "DirectSites": [],
        "DirectPackages": [],
        "DirectIp": [
            "geoip:private"
        ]
    },
    "json_template": {
        "dns": {
            "servers": [
                "8.8.8.8",
                {
                    "address": "77.88.8.8",
                    "domains": [
                        "geosite:category-ru"
                    ]
                }
            ],
            "queryStrategy": "UseIPv4"
        },
        "routing": {
            "rules": {},
            "domainStrategy": "AsIs"
        },
        "inbounds": [],
        "outbounds": [],
        "remarks": ""
    },
    "bypass_packages": [],
    "webui_passwords": {},
    "webui_users": {},
    "funny_strings": ["fill this please"],
    "publicbot": {
        "token": "",
        "tg_lang": {},
        "lang": {
            "ru": {
                "btn_get_sub": "🔗 Получить подписку",
                "btn_info": "ℹ️ Информация",
                "btn_bonus": "🎁 Ввести бонусный код",
                "btn_lang": "🌐 Сменить язык",
                "btn_reset": "⚠ Сбросить подписку",
                "btn_support": "💬 Поддержка",
                "btn_logout": "⚠ Выйти",
                "btn_help": "ℹ Справка",
                "btn_delete": "❌ Удалить аккаунт",
                "btn_delete_confirm": "✅ Удалить аккаунт",
                "btn_cancel": "🔙 Отменить",
                "btn_settings": "⚙ Настройки",
                "btn_chart": "📊 Мой трафик",
                "btn_main_account": "⚙ Управление аккаунтом",
                "btn_main_sub": "⚙ Управление подпиской",
                "btn_main_back": "🔙 В главное меню",
                "btn_chart_days": "{days} дн.",
                "settings_menu": "⚙ <b>Настройки</b>\nВыберите что хотите изменить:",
                "settings_name_prompt": "✏ Введите новое отображаемое имя:",
                "settings_name_success": "✅ Имя успешно изменено.",
                "settings_fp_prompt": "🔒 Выберите отпечаток:",
                "settings_fp_success": "✅ Отпечаток изменён.",
                "settings_pass_prompt": "🔒 Введите новый пароль:",
                "settings_pass_success": "✅ Пароль изменён.",
                "settings_login_prompt": "📧 Введите новый логин:",
                "settings_login_success": "✅ Логин изменён.",
                "no_account": "⚠ У вас нету зарегистрированного аккаунта.",
                "confirm_delete": "⚠ <b>Вы уверены, что хотите удалить аккаунт?</b>\nЭто действие необратимо. Все данные будут удалены.\n\nНапишите \"удалить\" для подтверждения.",
                "delete_confirm_input": "удалить",
                "name_label": "✏ Имя",
                "fp_label": "🔒 Отпечаток",
                "pass_label": "🔑 Пароль",
                "login_label": "📧 Логин",
                "welcome_new": "👋 Добро пожаловать!\nЧтобы начать пользоваться интернетом без ограничений, нажмите «Получить подписку» и введите код приглашения.",
                "welcome_reg": "👋 С возвращением! Выберите нужное действие в меню ниже.",
                "enter_invite": "🔑 Пожалуйста, отправьте мне ваш код приглашения:",
                "invalid_code": "❌ Неверный код, либо он уже был использован.",
                "reg_success": "✅ Подписка успешно активирована!",
                "chart_text": "📊 График: последние <b>{days}</b> дней\n\n<b>За всё время</b>\n<b>Обычный трафик</b>\n⬆️ {upload} выгружено (Up)\n⬇️ {download} загружено (Down)\nЭтот месяц:\n📦 {used} / {limit} GB <i>({percent})</i>\n\n<b>Whitelist</b>\n⬆️ {upload} выгружено\n⬇️ {download} загружено\nЭтот месяц:\n📦 {wl_used} / {wl_limit} GB <i>({wl_percent})</i>",
                "reset_success": "✅ Ссылка сброшена. Не забудьте обновить в приложении!",
                "info_text": "ℹ️ <b>Ваш профиль:</b> <code>{username}</code>\nВключен: {status}\nДоступ к WL-локациям: {wl_status}\nВ сети: {online}\n\n📊 <b>Трафик:</b>\nСкачано за всё время: {total} MB\nВ этом месяце: {monthly} MB / {limit}\nWL за всё время: {wl_total} MB\nWL в этом месяце: {wl_monthly} MB / {wl_limit}\nПодробная информация:\nUp {up} MB | Down {down} MB\nWL Up {wl_up} MB | Down {wl_down} MB\n<i>wl — whitelist-локации</i>\n⏳ <b>Осталось времени:</b>\n{days}\nОтпечаток: {fingerprint}",
                "help_text": "ℹ️ <b>Описания профилей</b>\n\n{text}",
                "enter_bonus": "🎁 Отправьте бонусный код для пополнения времени/трафика:",
                "bonus_success": "✅ Бонусный код успешно применен! Ваш тариф обновлен.",
                "logout_success": "✅ Вы вышли из аккаунта.",
                "enter_token": "🔑 Введите вашу ссылку или токен.",
                "support_text": "💬 По всем вопросам обращайтесь: @pomidorka_1515",
                "confirm_reset": "⚠ Вы уверены что хотите сбросить ссылку и айди подписки? Напишите \"согласен\" чтобы продолжить.",
                "choose_lang": "🌐 Выберите язык / Choose language:",
                "choose_chart_days": "Выберите кол-во дней.",
                "lang_set": "🇷🇺 Язык изменен на Русский.",
                "chart_generating": "⌛ Генерация графика...",
                "unlimited": "Безлимит",
                "lifetime": "Навсегда",
                "reset_confirm_input": "согласен",
                "cancelled": "🔙 Действие отменено. Главное меню:",
                "btn_login": "🔑 Войти",
                "btn_login_credentials": "По логину и паролю",
                "btn_login_token": "По ссылке",
                "enter_email": "📧 Введите ваш логин",
                "enter_pass": "🔒 Введите пароль:",
                "login_success": "✅ Успешный вход!",
                "delete_success": "✅ Аккаунт удален.",
                "login_fail": "❌ Неверный логин, пароль или токен.",
                "choose_login": "🔒 Как бы вы хотели войти?",
                "warning_disabled": "⚠ Ваша подписка истекла.",
                "warning_traffic": "⚠ Вы использовали <b>{used}</b> ГБ из <b>{available}</b> ГБ доступных вам.",
                "warning_traffic_disabled": "⚠ Вы использовали весь доступный вам трафик ({available} ГБ). Подписка была отключена.",
                "warning_traffic_whitelist": "⚠ Вы использовали <b>{used}</b> MB из <b>{available}</b> GB на БС локациях.",
                "warning_traffic_whitelist_disabled": "⚠ Вы использовали весь доступный Вам трафик на БС локациях ({available} ГБ). Они были отключены для вас.",
                "warning_days": "⚠ Осталось <b>{days}</b> дней до конца подписки.",
                "length_username": "❌ Слишком длинное имя пользователя. Максимальная длина: {ln} символов.",
                "length_displayname": "❌ Слишком длинное отображаемое имя. Максимальная длина: {ln} символов.",
                "get_sub_text": "**🚀 Ваша подписка готова!**\nОтсканируйте QR-код для получения ссылки или выберите способ подключения ниже.\n*⚠️ Никому не пересылайте это сообщение, оно содержит ваш личный ключ доступа.*",
                "get_sub_btn_link": "🌐 Открыть ссылку",
                "get_sub_btn_happ": "⚡ Добавить в Happ"
            },
            "en": {
                "btn_get_sub": "🔗 Get subscription",
                "btn_info": "ℹ️ Information",
                "btn_bonus": "🎁 Enter Bonus Code",
                "btn_lang": "🌐 Change Language",
                "btn_reset": "⚠ Reset subscription",
                "btn_support": "💬 Support",
                "btn_logout": "⚠ Logout",
                "btn_help": "ℹ Reference",
                "btn_delete": "❌ Delete account",
                "btn_delete_confirm": "✅ Yes, delete my account",
                "btn_cancel": "🔙 Cancel",
                "btn_settings": "⚙ Settings",
                "btn_chart": "📊 My usage",
                "btn_main_account": "⚙ Account management",
                "btn_main_sub": "⚙ Subscription management",
                "btn_main_back": "🔙 Go back",
                "btn_chart_days": "{days} d",
                "settings_menu": "⚙ <b>Settings</b>\nChoose what to change:",
                "settings_name_prompt": "✏ Enter your new display name:",
                "settings_name_success": "✅ Display name changed.",
                "settings_fp_prompt": "🔒 Choose a fingerprint:",
                "settings_fp_success": "✅ Fingerprint changed.",
                "settings_pass_prompt": "🔒 Enter your new password:",
                "settings_pass_success": "✅ Password changed.",
                "settings_login_prompt": "📧 Enter your new login:",
                "settings_login_success": "✅ Login changed.",
                "confirm_delete": "⚠ <b>Are you sure you want to delete your account?</b>\nThis action is irreversible. All data will be permanently removed.\n\nType \"delete\" to confirm.",
                "no_account": "⚠ You do not have a registered account.",
                "enter_token": "🔑 Enter your link or token.",
                "delete_confirm_input": "delete",
                "chart_generating": "⌛ Generating chart...",
                "name_label": "✏ Name",
                "fp_label": "🔒 Fingerprint",
                "pass_label": "🔑 Password",
                "login_label": "📧 Login",
                "btn_login_credentials": "With login and password",
                "btn_login_token": "With subscription link",
                "choose_login": "🔒 How would you like to log in?",
                "choose_chart_days": "Choose a day amount.",
